name: Build, Test, and Notify

env:
  IMAGE_TAG: ${{ github.sha }} # Set the image tag to the commit SHA
  REPO_NAME: my-python-project   # Name of the Docker repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # Check out the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # Use Python 3.8
        
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip # Upgrade pip to the latest version
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt # Install project dependencies

    - name: Run build script
      run: |
        echo "Running build script"  # Placeholder for actual build commands

    - name: Run tests
      run: |
        pytest  # Run tests using pytest

    - name: Build Docker image
      run: docker build . --tag abbasabs/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }} # Build Docker image with correct tagging

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u abbasabs --password-stdin # Login securely to Docker Hub

    - name: Push to Docker Hub  
      run: docker push abbasabs/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }} # Push the image to Docker Hub

    - name: Pull docker image file to EC2
      uses: appleboy/ssh-action@master
      with: 
          host: ${{ secrets.EC2_Public_IP}}
          username: ec2-user
          key: ${{ secrets.SSH_KEY_SECRET }}
          script: |
            sudo systemctl start docker
            sudo docker pull abbasabs/${{env.REPO_NAME}}:${{ env.IMAGE_TAG }}
            sudo docker run -d abbasabs/${{env.REPO_NAME}}:${{ env.IMAGE_TAG }}
 

  # Notification Job to notify on build failures
  notify:
    needs: build # This job depends on the build job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # Check out the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 # Use Python 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt # Install dependencies for notification

   #  - name: Send email notification on failure
   #    if: failure() # Only run if the build fails
   #    uses: dawidd6/action-send-mail@v2
   #    with:
   #      server_address: smtp.example.com
   #      server_port: 587
   #      username: ${{ secrets.EMAIL_USERNAME }} # Email username from secrets
   #      password: ${{ secrets.EMAIL_PASSWORD }} # Email password from secrets
   #      subject: 'Build Failed' # Email subject
   #      body: 'The build on branch ${{ github.event.pull_request.head.ref || github.event.ref }} failed. Please check the build logs for details.' # Email body
   #      from: 'abbasabs14@gmail.com' # Corrected email
   #      to: 'wazirali56@gmail.com' # Recipient email
