name: Build, Test, and Notify

# env:
#   IMAGE_TAG: ${{ github.sha }}
#   REPO_NAME: addreponame
  

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run build script
      run: |
        echo "Running build script"  # Replace with your actual build/compile commands

    - name: Run tests
      run: |
        pytest  # Replace with your testing commands, e.g., pytest


    - name: build docker image
      run: docker build . --tag my-python-project:latest${{env.REPO_NAME}}:${{ env.IMAGE_TAG }}

    - name: login to docker hub
      run: docker login -u abbasabs -p Javascript1@

    - name: push to docker hub  
      run: docker push abbasabs${{env.REPO_NAME}}:${{ env.IMAGE_TAG }}

  #     - name: Pull docker image file to EC2
  #       uses: appleboy/ssh-action@master
  #       with: 
  #         host: ${{ secrets.EC2_Public_IP}}
  #         username: ec2-user
  #         key: ${{ secrets.SSH_KEY_SECRET }}
  #         script: |
  #           sudo systemctl start docker
  #           sudo docker pull linvest21sie/${{env.REPO_NAME}}:${{ env.IMAGE_TAG }}
  #           sudo docker run -d linvest21sie/${{env.REPO_NAME}}:${{ env.IMAGE_TAG }}

  # Notification Job, helps to get notification on build failure or passing.
  notify:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Send email notification on failure
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.example.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: 'Build Failed'
        body: 'The build on branch ${{ github.event.pull_request.head.ref || github.event.ref }} failed. Please check the build logs for details.'
        from: 'abbasabs14@gmail.com.com'
        to: 'wazirali56@gmail.com.com'

 