name: Hello world workflow

on:
  push
    branches:
       - main
pull_request:
    branches:
       - main
workflow_dispatch:

jobs:
   hello:
	runs-on: ubantu-latest
	steps:
	   - uses: actions/checkout@v2
	   - run: echo"hello world"
           - shell: bash
goodbye:
	runs-on: ubantu-latest
	steps:
        - name: goodbye world
	  run: echo "goodbye world"
          shell: bash			

	
